version: "3.6"
services:
  postgres:
    image: postgres:14.6-alpine
    env_file:
      - ./backend/src/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    ports:
      - "5433:5432"
  app:
    
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn src.main:app --host 0.0.0.0  --port 8000
    # command: uvicorn src.main:app --host 0.0.0.0  --port 443 --ssl-certfile=./0.0.0.0.crt --ssl-keyfile=./0.0.0.0.key
    # command: ls
    ports:
      # - 443:443
      - 8000:8000
    volumes:
      - ./backend:/app
  nginx:
    image: nginx:latest
    hostname: api-nginx
    container_name: api-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d
    depends_on:
      - app

volumes:
  postgres_data:
